#include "..\\catch_amalgamated.hpp"
#include "sortedSingle.h"
#include <sstream>
using std::ostringstream;

/*****************************************************************************
 * do not edit this file
 ****************************************************************************/



